### ISSUE TITLE
运行挂掉

### ISSUE THREAD

**Issue by kulong51** [gqjjqg/android-extend#15]
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.xxxx-1/lib/arm/librender.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.guo.android_extend.GLES2Render.<clinit>(GLES2Render.java:15)
        at com.guo.android_extend.widget.CameraGLSurfaceView.onSurfaceChanged(CameraGLSurfaceView.java:78)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1511)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by gqjjqg** [comment]
so缺失了，编译问题？？

**Comment by kulong51** [comment]
已经找到原因解决，混淆导致的问题
 -keep class com.arcsoft.ageestimation.**{*;}
 -keep class com.arcsoft.facedetection.**{*;}
 -keep class com.arcsoft.facerecognition.**{*;}
 -keep class com.arcsoft.facetracking.**{*;}
 -keep class com.arcsoft.genderestimation.**{*;}
 -keep class com.guo.android_extend.{*;}
-keep  class com.guo.android_extend.** { *; }
-keepclasseswithmembernames class * {
    native <methods>;
}
-libraryjars libs/armeabi/libArcSoft_AEEngine.so
-libraryjars libs/armeabi/libArcSoft_FDEngine.so
-libraryjars libs/armeabi/libArcSoft_FREngine.so
-libraryjars libs/armeabi/libArcSoft_FTEngine.so
-libraryjars libs/armeabi/libArcSoft_GEEngine.so
-libraryjars libs/armeabi/libmpbase.so

-libraryjars libs/armeabi-v7a/libArcSoft_AEEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FDEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FREngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_FTEngine.so
-libraryjars libs/armeabi-v7a/libArcSoft_GEEngine.so
-libraryjars libs/armeabi-v7a/libmpbase.so
