### ISSUE TITLE
ImageConverter  : FORMAT NOT SUPPORT THIS SIZE

### ISSUE THREAD

**Issue by CangJie2016** [gqjjqg/android-extend#28]
Caused by: java.lang.Exception: FORMAT NOT SUPPORT THIS SIZE
        at com.guo.android_extend.image.ImageConverter.image_init(Native Method)
        at com.guo.android_extend.image.ImageConverter.initial(ImageConverter.java:43)

**Comment by gqjjqg** [comment]
NV21 格式 尺寸=W * H * 3 / 2
因此宽和高必须至少有一个是偶数，实际上要求宽为偶数，高可以为奇数。
ImageConverter 目的只做转换，不做裁剪适配，因此不支持。
